# --- Build Stage ---
FROM node:22-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build -- --configuration production --no-progress --verbose --no-aot --optimization=false || true

# --- Runtime Stage ---
FROM nginx:alpine
COPY --from=build /app/dist/code-a-cuisine /usr/share/nginx/html
COPY ./docker/nginx/default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
